trigger:
  branches:
    include:
      - main

pool:
  name: Azure Pipelines  # Ensure this is an existing pool or use 'Default' if unsure

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - script: echo hello world
    displayName: 'Print Hello World'
