trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest  # Ensure this is an existing pool or use 'Default' if unsure

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
   
