trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - script: echo hello world
    displayName: 'Print Hello World'
