trigger:
  branches:
    include:
      - main

pool:  
  name: MyCustomPool

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'